# Generated by Django 2.2.6 on 2019-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.SlugField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.SlugField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
