# Generated by Django 2.2.6 on 2019-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191119_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=True),
        ),
    ]
