# Generated by Django 2.2.6 on 2019-11-22 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='man_profile',
            new_name='managers',
        ),
        migrations.RenameModel(
            old_name='ten_profile',
            new_name='tenants',
        ),
    ]
