# Generated by Django 2.2.6 on 2019-11-22 09:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20191122_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='managers',
            new_name='manager',
        ),
        migrations.RenameModel(
            old_name='tenants',
            new_name='tenant',
        ),
    ]
